# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvxN9EO_1sUNEABLcFLmsFlBRpeSBFgJ
"""

"""
@author: Çağatay Yaman 120200029
@author: Vedat Vatan 120200148
@author: Uğur Türkel, 119200070
https://github.com/Ugurmutturkel/Cmpe331-Project001

"""

import requests
from bs4 import BeautifulSoup


url = 'https://www.airbnb.com.tr/'
page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")

house_name= dict()
house_prices = []
house_ratings = []
house_names = []

price_i = 0
rating_i = 0

for house_name in soup.find_all('div',attrs={'class':'t1jojoys dir dir-ltr'}):
    house_names.append(house_name.get_text()) 

for house_rating in soup.find_all('span',attrs={'class':'r1dxllyb dir dir-ltr'}):
    house_ratings.append(house_rating.get_text())
for house_price in soup.find_all('span', attrs={'class':'a8jt5op dir dir-ltr'}):
    house_prices.append(house_price.get_text())


for i in range(0,len(house_names)):
    print("House Name:",house_names[i], "\n AirBNB Rating:",house_ratings[i],"\n AirBNB Prices:",house_prices[i],sep="")
    print('')